## **SPAM VS HAM** Dataset

In [ ]:
import pandas as pd
import numpy as np

 ***DATA CLEANING***

In [8]:
df=pd.read_csv("../data/spam.csv",encoding='latin-1')

In [ ]:
# As we can see there are some unwanted columns in the dataset, so we will drop those columns and keep only the required columns for our model building.
df.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [10]:
# Keep only needed columns
df = df[['v1', 'v2']]
df.columns = ['label', 'text']
df.head()

  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

No filled is missing

In [11]:
#Missing values
df.isnull().sum()

label    0
text     0
dtype: int64

In [12]:
df['label'].value_counts()

label
ham     4825
spam     747
Name: count, dtype: int64